# Add this file 
# Initial login username is admin ,password is admin
# echo -n "Enter Password: " && head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1 to create new administrator password
# this docker-compose make from https://docs.graylog.org/en/4.0/pages/installation/docker.html#quick-start

version: '3.8'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:${DB_MONGO_VERSION}
    container_name: ${APP_CONTAINER_NAME}-mongo
    restart: always
    volumes: 
      - ${VOLUMES_PATH_PREFIX}/mongodb:/data/db
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.16.0
    container_name: ${APP_CONTAINER_NAME}-elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    restart: always
    volumes: 
      - elasticsearch:/usr/share/elasticsearch/data
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # echo -n admin | shasum -a 256, default password is admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=${APP_PASSWORD}
      - GRAYLOG_HTTP_EXTERNAL_URI=${APP_SITE_URL}
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - ${APP_PORT}:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    volumes: 
      - graylog:/usr/share/graylog/data/
      - ${VOLUMES_PATH_PREFIX}/plugin:/usr/share/graylog/plugin

volumes: 
  graylog:
  elasticsearch:
  
networks:
  default:
      name: ${APP_NETWORK}
